### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by khoait** [khoait/DCE.PCF#102]
### Overview

There is no OOTB control to display and update time value without the date part of a Date Time field.

#### Intended outcome

Ability to quickly update the time part of a DateTime field.

### Features
- [x] Supports new look
- [x] Use date part from another DateTime field
- [x] Placeholder
- [x] Increment step
- [x] Use 12-hour or 24-hour format
- [x] Freeform
- [x] start hour, end hour
